# Generated by Django 5.2.1 on 2025-06-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.AutoField(help_text='Código único do produto', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do produto', max_length=70)),
                ('preco_compra', models.FloatField(help_text='Informe o preço de compra do produto')),
                ('preco_venda', models.FloatField(help_text='Informe o preço de venda do produto')),
                ('cor', models.CharField(help_text='Informe a cor do produto', max_length=20)),
                ('dt_fabricacao', models.DateField(help_text='Informe a data de fabricação do produto')),
                ('imagem', models.CharField(help_text='Informe o nome da imagem do produto', max_length=25)),
            ],
        ),
    ]
