# Generated by Django 5.2.1 on 2025-06-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('codigo', models.AutoField(help_text='Informe o Código do fabricante', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do fabricante', max_length=70)),
            ],
        ),
    ]
